### ISSUE TITLE
lab3_2 review

### ISSUE THREAD

**Issue by AndreevP** [python-practice-b02-927/Elesin-Leonid#21]
В целом при рисовании картинки вы следовали инструкциям, поэтому за это задание получаете полный балл. То что вы сделали рабочую анимацию на задачу 3-х тел также похвально, но почему-то при выполнении этого задания вы совершенно забили на структуру кода и читабельность - не делайте так больше. 
 Хоть pep8 и не видит явной ошибки в выражениях вида:
`((xe-xm)**2+(ye-ym)**2)**0.5` 
Он все же рекомендует писать их, группируя члены выражения (это повышает читабельность)
`((xe-xm)**2 + (ye-ym)**2)**0.5`

**Comment by PeganovAnton** [comment]
@LeoYe-st , это полиция issue. Вы должны отвечать в комментариях на сделанные замечания.

**Comment by LeoYe-st** [comment]
Я просто не понял как мне ответить, а со знаками я вроде исправил
